#' Compute Purity of Tumor Samples
#'
#' Estimate the proportion of cancer cells in the admixture of cells
#' forming tumor microenvironment.
#'
#' @param tumor_table A matrix of beta-values from tumor samples.
#' @param list_of_sites A list of indexes generated by
#' \code{\link{select_informative_sites}} or
#' \code{\link{select_informative_regions}}.
#' @return A vector of purity estimates.
#' @importFrom stats median
#' @export
#' @examples
#' purity <- compute_purity(tumor_toy_data, list(hyper=c(1, 10, 20), hypo=c(15,30,45)))
compute_purity <- function(tumor_table, list_of_sites) {
  message(sprintf("[%s] # Compute purity #", Sys.time()))
  # check parameters
  assertthat::assert_that(is.list(list_of_sites))
  assertthat::assert_that(any(names(list_of_sites) %in% c("hyper", "hypo")))
  diff_range_t <- diff(range(tumor_table, na.rm = TRUE))
  if (diff_range_t < 0 | diff_range_t > 100){
      stop("Unexpected range of beta values.")
  } else if (diff_range_t <= 1){
      max_purity <- 1
  } else if (diff_range_t <= 100) {
      max_purity <- 100
  }

  beta_values <- rbind(tumor_table[list_of_sites[["hyper"]],],
                       max_purity - tumor_table[list_of_sites[["hypo"]],])
  purity <- apply(beta_values, 2, median, na.rm = TRUE)
  message(sprintf("[%s] Done",  Sys.time()))
  return(purity)
}
