#' Compute Area Under Curve
#'
#' This function compute the Area Under Curve used to define the segregation
#' between tumor and normal samples according to their beta-score.
#'
#' @param tumor a matrix of beta scores generated by an Illumina BeadChip.
#' @param control a matrix of beta scores generated by an Illumina BeadChip.
#' @param max_NAs_fraction fraction of NAs (considered independently in tumor and
#' control samples) above which a site will not be selected (default=0.5).
#' @param n_threads number of cores to use
#' @param outfile optionally save auc vector as an RData file
#' @return a vector of AUC scores
#' @export
compute_AUC <- function(tumor, control, max_NAs_frac=0.5, n_threads=1, outfile=NULL){
    max_threads <- parallel::detectCores()
    n_threads <- as.integer(n_threads)
    stopifnot(is.integer(n_threads))
    if (n_threads > max_threads) {
        stop(sprintf("selected more than available (%i) threads", max_threads))
    }
    stopifnot(max_NAs_frac >= 0 | max_NAs_frac <= 1)
    stopifnot(nrow(tumor) == nrow(control))

    message(sprintf("[%s] Checking per-row NAs fraction...",  Sys.time()))
    auc <- rep(NA, nrow(tumor))
    valid_tumor_row_logi <- apply(tumor, 1, function(x) sum(is.na(x)) / length(x) < max_NAs_frac)
    valid_control_row_logi <- apply(control, 1, function(x) sum(is.na(x)) / length(x) < max_NAs_frac)
    valid_row_idx <- which(valid_tumor_row_logi & valid_control_row_logi)

    full_table <- cbind(tumor[valid_row_idx, ], control[valid_row_idx, ])
    state <- c(rep(1, ncol(tumor)), rep(0, ncol(control)))
    message(sprintf("[%s] Computing AUC with %s process(es)...",  Sys.time(), n_threads))
    cl <- parallel::makeCluster(n_threads)
    valid_auc <- parallel::parRapply(cl, full_table, function(x){
        non_NA_idx <- which(!is.na(x))
        roc <- ROC::rocdemo.sca(truth=state[non_NA_idx], data=x[non_NA_idx], cutpts=seq(0, 1, .01))
        ROC::AUC(roc)
    })
    parallel::stopCluster(cl)
    auc[valid_row_idx] <- valid_auc
    message(sprintf("[%s] Done.",  Sys.time()))
    if (!is.null(outfile)) {
        try(save(auc, file=outfile))
    }
    return(auc)
}
