#' Compute Purity of Tumor Samples
#'
#' Estimate the proportion of cancer cells in the admixture of cells
#' forming tumor microenvironment.
#'
#' @param tumor_table A matrix of beta-values (percentage) from tumor samples.
#' @param list_of_sites A list of indexes generated by
#' \code{\link{select_informative_sites}} or
#' \code{\link{select_informative_sites}} to be used to compute purity.
#' @return A vector of purity estimates.
#' @importFrom stats median
#' @export
#' @examples
#' purity <- compute_purity(tumor_toy_data, list(hyper=c(1, 10, 20), hypo=c(15,30,45)))
compute_purity <- function(tumor_table, list_of_sites, tumor) {
  assertthat::assert_that(is.list(list_of_sites))
  assertthat::assert_that(length(list_of_sites) == 2)
  assertthat::assert_that(all(names(list_of_sites) %in% c("hyper", "hypo")))
  if (!missing(tumor) || !missing(control)){
    warning("'tumor' is deprecated. Use 'tumor_table' instead.")
    tumor_table <- tumor
  }
  beta_values <- rbind(tumor_table[list_of_sites[["hyper"]],],
                       1 - tumor_table[list_of_sites[["hypo"]],])
  purity <- apply(beta_values, 2, median, na.rm=TRUE)
  return(purity)
}
