#' Compute Purity of Tumor Samples
#'
#' Estimate the proportion of cancer cells in the admixture of cells
#' constituting tumor microenvironment.
#'
#' @param tumor a matrix of beta scores generated from an Illumina
#' BeadChip (rows=sites; columns=samples).
#' @param list_of_sites a list of indexes generated by \code{\link{select_informative_sites}}
#' to be used to compute purity.
#'
#' @return a vector of purity estimates.
#' @export
#' @examples
#' \dontrun{
#' purity <- compute_purity(tumor, list_of_sites)
#' }
compute_purity <- function(tumor, list_of_sites) {
    tumor <- as.matrix(tumor)
    assertthat::assert_that(is.list(list_of_sites),
                length(list_of_sites) == 2,
                all(names(list_of_sites) %in% c("hyper", "hypo")) )

    beta_values <- rbind(tumor[list_of_sites[["hyper"]],],
                         1 - tumor[list_of_sites[["hypo"]],])
    purity <- apply(beta_values, 2, median, na.rm=T)
    return(purity)
}
