#' PAMES: Purity Assessment from clonal MEthylation Sites
#'
#' The PAMES package provides a set of functions to estimate
#' the level of purity of tumor samples.
#'
#' The two main functions of PAMES are \code{\link{select_informative_sites}}
#' (to retreive sites of interest), and \code{\link{compute_purity}} (to compute
#' purity of tumor samples providing a list of sites generated by
#' \code{\link{select_informative_sites}}). Additionally, if working with
#' Bisulphite Sequencing data, users must first map their set of CpG sites to CpG islands 
#' with \code{\link{compute_islands_indexes}}, reduce the data with \code{\link{reduce_to_islands}},
#' select informative CpG islands with \code{\link{select_informative_islands}} and finally
#' estimate purity with \code{\link{compute_purity}}.
#
#' @docType package
#' @name PAMES
NULL
