#' Convert beta values from Bisulphite Sequencing to single CpG island beta values
#'
#' Reduce beta values from different CpG sites to single beta values
#' associated to one CpG island where CpG sites are located.
#'
#' Bisulphite Sequencing is used to retrieve level of DNA methylation at
#' base resolution. Different experiments may retrieve
#' different CpG sites. This function makes a direct comparison possible.
#'
#' @param cpg_sites_matrix a matrix of beta values.
#' @param cpg_indexes a list of indexes generated by \code{compute_islands_indexes}.
#' @param min_CpGs an integer (default to 3). Minimum number of CpG sites within
#' a single CpG island required to compute the reduced beta value (return NA otherwise).
#' @return a matrix of beta values (nrow == length(cpg_indexes)).
#' @importFrom stats median
#' @export
#' @examples
#' reduced_tumor <- reduce_to_islands(bs_tumor_toy_data, bs_toy_indexes)
#' reduced_control <- reduce_to_islands(bs_control_toy_data, bs_toy_indexes)
reduce_to_islands <- function(cpg_sites_matrix, cpg_indexes, min_CpGs = 3){
  stopifnot(is.list(cpg_indexes))
  cpg_sites_matrix <- as.matrix(cpg_sites_matrix)
  message(sprintf("[%s] Reducing beta values...",  Sys.time()))
  cpg_islands_matrix <- do.call("rbind",
    lapply(cpg_indexes, function(idx){
      reduce_island(cpg_sites_matrix[idx, , drop = F], min_CpGs)})
  )
  if (is.null(names(cpg_indexes))) {
    names(cpg_indexes) <- paste0("cpg", seq(1, length(cpg_indexes)))
  }
  rownames(cpg_islands_matrix) <- names(cpg_indexes)
  message(sprintf("[%s] Done",  Sys.time()))
  return(cpg_islands_matrix)
}

#' Reduce a matrix subset
#'
#' Takes into consideration the eventual presence of NAs
#' @param matrix_subset a matrix
#' @param n minimum required number of sites per island (return NA otherwise)
#' @keywords internal
reduce_island <- function(matrix_subset, n) {
  if (nrow(matrix_subset) < n) {
    beta_values <- NA
  } else {
    # identify sites without any beta-score
    all_NAs_sites <- rowSums(is.na(matrix_subset)) == ncol(matrix_subset)
    if (sum(!all_NAs_sites) < n) {
      beta_values <- NA
    } else {
      beta_values <- apply(matrix_subset, 2, median, na.rm = T)
    }
  }
  return(beta_values)
}
