#' Select informative CpG islands
#'
#' Generate a list of informative CpG islands to be used to compute purity of
#' a set of tumor samples.
#'
#' Informative islands are divided into \code{hyper} and \code{hypo} depending on their level of
#' methylation with respect to the average beta value of normal samples.
#' Both sets will be used to compute purity.
#'
#' @param tumor a matrix of beta scores generated by BS technology.
#' Applied independently to each island (row).
#' @param auc a vector of AUC scores generated by \code{compute_AUC}.
#' @param max_sites maximum number of islands to retrieve (half hyper-,
#' half hypo-methylated) (default=20).
#' @param hyper_range a vector of length two with minimum lower and upper values required to
#' select hyper-methylated informative sites
#' @param hypo_range a vector of length two with minimum lower and upper values required to
#' select hypo-methylated informative sites
#' @return a list of indexes of informative islands (divided into two sets:
#' "hyper"- and "hypo"-methylated).
#' @importFrom stats na.omit
#' @export
#' @examples
#' reduced_tumor <- reduce_to_islands(bs_tumor_toy_data, bs_toy_indexes)
#' reduced_control <- reduce_to_islands(bs_control_toy_data, bs_toy_indexes)
#' auc_data <- compute_AUC(reduced_tumor, reduced_control)
#' info_sites <- select_informative_islands(reduced_tumor, auc_data)
select_informative_islands <- function(tumor, auc, hyper_range = c(min = .40, max = .90),
  hypo_range = c(min = .10, max = .60), max_sites = 20){
    # check parameters ---------------------------------------------------------
    if (max_sites %% 2 != 0 & !is.integer(max_sites))
        stop("'max_sites' must be even")

    tumor   <- as.matrix(tumor)
    if (any(tumor < 0 | tumor > 1, na.rm=T))
        stop("Beta values in 'tumor' matrix must be decimal.")

    # minimum and maximum beta per site ----------------------------------------
    beta_max <- suppressWarnings(apply(tumor, 1, max, na.rm=T))
    beta_min <- suppressWarnings(apply(tumor, 1, min, na.rm=T))
    hyper_idx <- which(beta_min < hyper_range[1] & beta_max > hyper_range[2] & auc > .80)
    hypo_idx  <- which(beta_min < hypo_range[1]  & beta_max > hypo_range[2]  & auc < .20)

    message(sprintf("[%s] Total hyper-methylated sites = %i", Sys.time(), length(hyper_idx)))
    message(sprintf("[%s] Total hypo-methylated sites = %i",  Sys.time(), length(hypo_idx)))

    ordered_hyper_idx <- hyper_idx[order(auc[hyper_idx], decreasing=T)]
    ordered_hypo_idx  <- hypo_idx[order(auc[hypo_idx], decreasing=F)]

    top_hyper_idx <- ordered_hyper_idx[seq(max_sites/2)]
    message(sprintf("[%s] Hyper-sites selection: %i", Sys.time(),
                length(na.omit(top_hyper_idx))))

    top_hypo_idx <- ordered_hypo_idx[seq(max_sites/2)]
    message(sprintf("[%s] Hypo-sites selection: %i", Sys.time(),
                    length(na.omit(top_hypo_idx))))

    return(list(hyper=top_hyper_idx, hypo=top_hypo_idx))
}
