#' Select informative regions
#'
#' This function generates a list of informative regions to be used to estimate
#' the purity of a set of tumor samples.
#'
#' Informative regions are divided into \code{hyper} and \code{hypo} depending
#' on their level of methylation with respect to the average beta-score of
#' normal samples. Both sets will be used to compute purity.
#'
#' @param tumor_table A matrix of beta-values (percentage) from tumor samples.
#' @param auc A vector of AUC scores generated by \code{compute_AUC}.
#' @param max_sites Maximum number of regions to retrieve (half hyper-, half
#' hypo-methylated) (default = 20).
#' @param hyper_range A vector of length 2 with minimum lower and upper values
#' required to select hyper-methylated informative sites.
#' @param hypo_range A vector of length 2 with minimum lower and upper values
#' required to select hypo-methylated informative sites.
#' @param method How to select sites: "even" (half hyper-, half hypo-methylated sites),
#' "top" (highest AUC irregardless of hyper or hypomethylation), "hyper" (hyper-methylated sites only),
#' "hypo" (hypo-methylated, sites only).
#' @param percentiles Vector of length 2: lower and upper percentiles to
#' select sites with beta values outside hypo- and hyper-ranges (default =
#' 0,100; 0th and 100th percentiles, i.e. only min and max beta should be outside of ranges).
#' @return A named list of indexes of informative regions ("hyper-" and "hypo-methylated").
#' @importFrom dplyr "%>%"
#' @export
#' @examples
#' reduced_data <- reduce_to_regions(bs_toy_matrix, bs_toy_sites, cpg_islands[1:1000,])
#' auc_data <- compute_AUC(reduced_data[,1:10], reduced_data[,11:20])
#' info_regions <- select_informative_regions(reduced_data[,1:10], auc_data)
select_informative_regions <- function(tumor_table, auc, max_sites = 20,
    hyper_range = c(min = 40, max = 90), hypo_range = c(min = 10, max = 60),
    method = c("even", "top", "hyper", "hypo"), percentiles = c(0, 100), return_info=FALSE){

    message(sprintf("[%s] # Select informative regions #", Sys.time()))
    # check parameters
    diff_range_t <- diff(range(tumor_table, na.rm = TRUE))
    assertthat::assert_that(diff_range_t > 1, diff_range_t <= 100, msg="For computation efficiency convert tumor_table to percentage values.")

    tumor_table <- as.matrix(tumor_table)
    tumor_table <- round(tumor_table)
    storage.mode(tumor_table) <- "integer"

    assertthat::assert_that(nrow(tumor_table) == length(auc))

    assertthat::assert_that(is.numeric(max_sites))

    assertthat::assert_that(is.numeric(hyper_range))
    assertthat::assert_that(is.numeric(hypo_range))
    assertthat::assert_that(is.numeric(percentiles))

    assertthat::assert_that(length(hyper_range) == 2)
    assertthat::assert_that(length(hypo_range) == 2)
    assertthat::assert_that(length(percentiles) == 2)

    assertthat::assert_that(all(dplyr::between(hyper_range, 0, 100)))
    assertthat::assert_that(all(dplyr::between(hypo_range, 0, 100)))
    assertthat::assert_that(all(dplyr::between(percentiles, 0, 100)))

    method <- match.arg(method)
    if (method == "even")
        assertthat::assert_that(max_sites %% 2 == 0, msg="method is set to 'even' but max_sites is not even")

    assertthat::assert_that(is.logical(return_info))

    message(sprintf("- Method: %s", method))
    message(sprintf("- Number of regions to retrieve: %i", max_sites))
    message(sprintf("- Hyper-methylated regions range: %i-%i", hyper_range[1], hyper_range[2]))
    message(sprintf("- Hypo-methylated regions range: %i-%i", hypo_range[1], hypo_range[2]))
    message(sprintf("- Percentiles: %ith-%ith", percentiles[1], percentiles[2]))

    # minimum and maximum beta per region
    message(sprintf("[%s] Evaluating sites...", Sys.time()))
    min_beta <- suppressWarnings(apply(tumor_table, 1, quantile, probs = percentiles[1]/100, na.rm = TRUE))
    max_beta <- suppressWarnings(apply(tumor_table, 1, quantile, probs = percentiles[2]/100, na.rm = TRUE))

    diff_meth_regions <- dplyr::tibble(Index = seq_along(auc),
                                       AUC = auc,
                                       Max_beta = max_beta,
                                       Min_beta = min_beta) %>%
        dplyr::mutate(Type = dplyr::case_when(AUC > .80 & Min_beta < hyper_range[1] & Max_beta > hyper_range[2] ~ "Hyper",
                                              AUC < .20 & Min_beta < hypo_range[1]  & Max_beta > hypo_range[2]  ~ "Hypo",
                                              TRUE ~ "No_diff")) %>%
        dplyr::filter(Type != "No_diff") %>%
        dplyr::mutate(AUC = dplyr::if_else(Type == "Hypo", 1-AUC, AUC)) %>%
        dplyr::arrange(-AUC)

    regions_hyper <- dplyr::filter(diff_meth_regions, Type == "Hyper")
    regions_hypo <- dplyr::filter(diff_meth_regions, Type == "Hypo")
    message(sprintf("* Total hyper-methylated regions = %i", nrow(regions_hyper)))
    message(sprintf("* Total hypo-methylated regions = %i", nrow(regions_hypo)))

    if (method == "even") {
        regions <- list(hyper = regions_hyper %>% dplyr::slice(seq_len(max_sites/2)) %>% dplyr::pull(Index),
                        hypo  = regions_hypo  %>% dplyr::slice(seq_len(max_sites/2)) %>% dplyr::pull(Index))
    } else if (method == "top") {
        top_regions <- dplyr::bind_rows(regions_hyper, regions_hypo) %>% dplyr::arrange(-AUC) %>% dplyr::slice(seq_len(max_sites))
        regions <- list(hyper = top_regions %>% dplyr::filter(Type == "Hyper") %>% dplyr::pull(Index),
                        hypo  = top_regions %>% dplyr::filter(Type == "Hypo")  %>% dplyr::pull(Index))
    } else if (method == "hyper") {
        regions <- list(hyper = regions_hyper %>% dplyr::slice(seq_len(max_sites)) %>% dplyr::pull(Index))
    } else if (method == "hypo") {
        regions <- list(hypo = regions_hypo %>% dplyr::slice(seq_len(max_sites)) %>% dplyr::pull(Index))
    }

    message(sprintf("* Retrieved hyper-methylated regions = %i", length(regions$hyper)))
    message(sprintf("* Retrieved hypo-methylated regions = %i", length(regions$hypo)))

    message(sprintf("[%s] Done", Sys.time()))
    if (return_info) {
        return(list(regions, diff_meth_regions))
    } else {
        return(regions)
    }
}
