#' Select informative CpG islands
#'
#' Generate a list of informative CpG islands to be used to compute purity of
#' a set of tumor samples.
#'
#' Informative islands are divided into \code{hyper} and \code{hypo} depending on their level of
#' methylation with respect to the average beta value of normal samples.
#' Both sets will be used to compute purity.
#'
#' @param tumor a matrix of beta scores generated by BS technology.
#' @param control a matrix of beta scores generated by BS technology.
#' @param max_NAs_fraction fraction of NAs above which an island will not be selected (default=0.5).
#' Applied independently to each island (row).
#' @param max_sites maximum number of islands to retrieve (half hyper-,
#' half hypo-methylated) (default=20).
#' @return a list of indexes of informative islands (divided into two sets:
#' "hyper-" and "hypo-methylated").
#' @examples
#' \dontrun{
#' info_sites <- select_informative_islands(mapped_bs_tumor_toy_data_,
#'                                          mapped_bs_control_toy_data)
#' }
#' @export

select_informative_islands <- function(tumor,
                                       control,
                                       max_NAs_fraction=0.5,
                                       max_sites=20){
    # check parameters ---------------------------------------------------------
    if (max_sites %% 2 != 0 & !is.integer(max_sites))
        stop("'max_sites' must be even")
    if (max_NAs_fraction < 0 | max_NAs_fraction > 1)
        stop("'max_NAs_fraction' must be positive and lower than or equal to 1")

    tumor   <- as.matrix(tumor)
    control <- as.matrix(control)

    if (any(tumor < 0 | tumor > 1, na.rm=T) | any(control < 0 | control > 1, na.rm=T))
        stop("Beta values in 'tumor' and 'control' matrixes must be decimal.")

    # compute AUC --------------------------------------------------------------
    full_table <- cbind(tumor, control)
    state <- c(rep(1, ncol(tumor)), rep(0, ncol(control)))
    message(sprintf("[%s] Computing AUC...",  Sys.time()))
    auc <- apply(full_table, 1, function(meth_site){
        NAs_tumor   <- too_many_NAs(meth_site[state==1], max_NAs_fraction)
        NAs_control <- too_many_NAs(meth_site[state==0], max_NAs_fraction)
        if (NAs_tumor | NAs_control) {
            ans <- NA
        } else {
            non_NA_idx <- which(!is.na(meth_site))
            roc <- ROC::rocdemo.sca(truth=state[non_NA_idx],
                                    data=meth_site[non_NA_idx],
                                    cutpts=seq(0, 1, .01))
            ans <- ROC::AUC(roc)
        }
        return(ans)
    })
    message(sprintf("[%s] Done.",  Sys.time()))

    # compute beta-differences -------------------------------------------------
    tumor_median    <- apply(tumor, 1, median, na.rm=T)
    control_median  <- apply(control, 1, median, na.rm=T)
    beta_difference <- tumor_median - control_median

    # minimum and maximum beta per site ----------------------------------------
    old_warn <- getOption("warn")
    options(warn=-1)
    beta_max <- apply(tumor, 1, max, na.rm=T)
    beta_min <- apply(tumor, 1, min, na.rm=T)
    options(warn=old_warn)
    hyper_idx <- which(beta_min < .40 & beta_max > .90 & auc > .80)
    hypo_idx  <- which(beta_min < .10 & beta_max > .60 & auc < .20)

    message(sprintf("[%s] Total hyper-methylated sites = %i", Sys.time(), length(hyper_idx)))
    message(sprintf("[%s] Total hypo-methylated sites = %i",  Sys.time(), length(hypo_idx)))

    ordered_hyper_idx <- hyper_idx[order(auc[hyper_idx], decreasing=T)]
    ordered_hypo_idx  <- hypo_idx[order(auc[hypo_idx], decreasing=F)]

    top_hyper_idx <- ordered_hyper_idx[seq(max_sites/2)]
    message(sprintf("[%s] Hyper-sites selection: %i", Sys.time(),
                length(na.omit(top_hyper_idx))))

    top_hypo_idx <- ordered_hypo_idx[seq(max_sites/2)]
    message(sprintf("[%s] Hypo-sites selection: %i", Sys.time(),
                    length(na.omit(top_hypo_idx))))

    return(list(hyper=top_hyper_idx, hypo=top_hypo_idx))
}
