#' Select CpG islands required to compute sample purity.
#'
#' Generate a list of islands to be used to compute purity of a set of tumor samples.
#' Informative islands are divided in "hyper" and "hypo" depending on their level of
#' methylation with respect to the average of normal samples. Both sets will be used.
#'
#' @param tumor A matrix of beta scores generated by an Illumina MethylChip
#' @param control A matrix of beta scores generated by an Illumina MethylChip
#' @param max_NAs_fraction Fraction of NAs above which AUC will not be computed
#' (set to 1 to avoid sites with any NA). Applied independently to each sites (row).
#' @param max_sites Maximum number of sites to retrieve
#' (divided in two sets: "hyper-" and "hypo-methylated")
#' @param min_distance Measured in bp (base pair), used to avoid selection
#' of CpG sites located within this distance from another.
#' @param platform '27k' or '450k' Illumina HumanMethylation BeadChip.
#' @param genome Currently support hg19 or hg38. Used to map probes to genome and
#' remove heavly clusterd probes.
#' @return A list indexes of informative sites (divided into two sets:
#' "hyper-methylated" and "hypo-methylated")
#' @export
#' @examples
#' select_informative_sites(tumor_matrix, control_matrix)
#' select_informative_sites(tumor_matrix, control_matrix, max_sites=40, min_distance=5000)

select_informative_islands <- function(tumor, control,
                                       max_NAs_fraction=0.5, max_sites=20){
    # check parameters ---------------------------------------------------------
    if (max_sites %% 2 != 0 & !is.integer(max_sites))
        stop ("'max_sites' must be an integer and even number")
    if (max_NAs_fraction < 0 | max_NAs_fraction > 1)
        stop("'max_NAs_fraction' must be positive and lower than or equal to 1")

    tumor   <- as.matrix(tumor)
    control <- as.matrix(control)

    if (any(tumor < 0 | tumor > 1, na.rm=T) | any(control < 0 | control > 1, na.rm=T))
        stop("Beta values in 'tumor' and 'control' matrixes must be decimal.")

    # compute AUC --------------------------------------------------------------
    full_table <- cbind(tumor, control)
    state <- c(rep(1, ncol(tumor)), rep(0, ncol(control)))
    cat(sprintf("[%s] Computing AUC...\n",  Sys.time()))
    auc <- apply(full_table, 1, function(meth_site){
        NAs_tumor   <- (too_many_NAs(meth_site[state==1], max_NAs_fraction))
        NAs_control <- (too_many_NAs(meth_site[state==0], max_NAs_fraction))
        if (NAs_tumor | NAs_control) {
            ans <- NA
        } else {
            non_NA_idx <- which(!is.na(meth_site))
            roc <- ROC::rocdemo.sca(truth=state[non_NA_idx],
                                    data=meth_site[non_NA_idx],
                                    cutpts=seq(0, 1, .01))
            ans <- ROC::AUC(roc)
        }
        return(ans)
    })
    cat(sprintf("[%s] Done.\n",  Sys.time()))

    # compute beta-differences -------------------------------------------------
    tumor_median    <- apply(tumor, 1, median, na.rm=T)
    control_median  <- apply(control, 1, median, na.rm=T)
    beta_difference <- tumor_median - control_median

    # minimum and maximum beta per site ----------------------------------------
    old_warn <- getOption("warn")
    options(warn=-1)
    beta_max <- apply(tumor, 1, max, na.rm=T)
    beta_min <- apply(tumor, 1, min, na.rm=T)
    options(warn=old_warn)
    hyper_idx <- which(beta_min < .40 & beta_max > .90 & auc > .80)
    hypo_idx  <- which(beta_min < .10 & beta_max > .60 & auc < .20)

    cat(sprintf("[%s] Total hyper-methylated sites = %i\n", Sys.time(), length(hyper_idx)))
    cat(sprintf("[%s] Total hypo-methylated sites = %i\n",  Sys.time(), length(hypo_idx)))

    ordered.hyper_idx <- hyper_idx[order(auc[hyper_idx], decreasing=T)]
    ordered.hypo_idx  <- hypo_idx[order(auc[hypo_idx], decreasing=F)]

    top_hyper_idx <- ordered.hyper_idx[seq(max_sites/2)]
    cat(sprintf("[%s] Hyper-sites selection: %i\n", Sys.time(),
                length(na.omit(top_hyper_idx))))

    top_hypo_idx <- ordered.hypo_idx[seq(max_sites/2)]
    cat(sprintf("[%s] Hypo-sites selection: %i\n", Sys.time(),
                length(na.omit(top_hypo_idx))))

    list(hyper=top_hyper_idx, hypo=top_hypo_idx)
}
